# Site settings
title: Cabinet Dr Bourgeois | Dental Jekyll Theme
description: "A responsive Jekyll theme for dental clinics."
baseurl: "/dentistsmile/" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Cabinet Dr Bourgeois
    hero_description: A responsive Jekyll theme for dental clinics.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency: 931 53 234
    email: easybeau@gmail.com
    address: Von schroeders 273, <br> Viña del mar - Chile

# Opening hours
lun_ven: 9:00 – 18:00
samedi: 10:00 – 17:00
dimanche: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2015 DentistSmile - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
